//@baseUrl = https://test.onesnzeroes.dev/api/v1
@baseUrl = http://localhost:3000/api/v1
//@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDE1OTkxOCwiZXhwIjoxNzY0MjQ2MzE4fQ.F4cgbpztBsNdEHzY-X5wUBmyPsX0GjN3595TyCfUlxk
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6InVzZXJAZW1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjUyMjQ0MTAsImV4cCI6MTc2NTMxMDgxMH0.54KNNJLDmu4_pC1Q-PS2iMozKUJ2jRo_uZ1Qs1ug_mw
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJ1c2VybmFtZSI6ImFsZWtzaSIsImVtYWlsIjoiZW1haWwzQHByb3ZpZGVyLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTIyNDgyOCwiZXhwIjoxNzY1MzExMjI4fQ.nzwywVSiB2AzP9AKIkR6C8ppRxwyCBVB-pPlKaGRl9E

### Get all products
GET {{baseUrl}}/product/all
Accept: application/json

### Add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Cheeseburger",
  "price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2],
  "default_product": true
}

### broken add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "product_name": "Cheeseburger",
  "product_price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2]
}

### Update a product (not implemented)
PUT {{baseUrl}}/product/6
Content-Type: application/json

{
  "price": 9.99
}

### Delete a product (not implemented)
DELETE {{baseUrl}}/product/1

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "aleksi",
  "password": "aleksi"
}

### Get me
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2Mzk5MTI5OSwiZXhwIjoxNzY0MDc3Njk5fQ.1VGdTnn1Jl7DoXljv816Eo8VmQtxJO_S4QePrg6EG98 


### Get me with invalid token
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer {{token}}


### Get me with valid token
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer {{adminToken}}

### Get user by id
GET {{baseUrl}}/user/4
Authorization: Bearer {{token}}
Accept: application/json

### Get all users
GET {{baseUrl}}/user/all
Accept: application/json
Authorization: Bearer {{token}}

### Post user
POST {{baseUrl}}/user/register
Content-Type: application/json
Accept: application/json

{
  "username": "illorder7",
  "password": "?6",
  "email": "email3provider.com"
}

### Post user
POST {{baseUrl}}/user/register
Content-Type: application/json
Accept: application/json

{
  "username": "user",
  "password": "user",
  "email": "user@email.com"
}

### Get orders by user id
GET {{baseUrl}}/order/byuser/6
Accept: application/json
Authorization: Bearer {{token}}

### Put status
PUT {{baseUrl}}/order/status/2
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "status": "preparing"
}

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "illorder3",
  "password": "fuckme?3"
}

### Get orders
GET {{baseUrl}}/order/all
Accept: application/json
Authorization: Bearer {{token}}

### Post order
POST {{baseUrl}}/order
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 8.99,
  "delivery_address":"delivery address",
  "user_id": 6,
  "product_ids": [2,5]
}

### Put order
PUT {{baseUrl}}/order/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "delivery_address":"new delivery address"
}

### Delete order
DELETE {{baseUrl}}/order/9
Content-Type: application/json
Authorization: Bearer {{token}}

### Put product
PUT {{baseUrl}}/product/12
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"new 2burger",
  "category": "burger"
}

### Delete product
DELETE {{baseUrl}}/product/12
Content-Type: application/json
Authorization: Bearer {{token}}

### Add product with image
POST {{baseUrl}}/product/add
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----BOUNDARY

------BOUNDARY
Content-Disposition: form-data; name="name"

Cheeseburger
------BOUNDARY
Content-Disposition: form-data; name="price"

8.99
------BOUNDARY
Content-Disposition: form-data; name="description"

Classic burger with cheese
------BOUNDARY
Content-Disposition: form-data; name="category"

main
------BOUNDARY
Content-Disposition: form-data; name="default_product"

true
------BOUNDARY
Content-Disposition: form-data; name="option_ids"

[1,2,4]
------BOUNDARY
Content-Disposition: form-data; name="allergen_ids"

[1,2]
------BOUNDARY
Content-Disposition: form-data; name="image"; filename="burger.jpg"
Content-Type: image/jpeg

< cheeseburger_test.jpg
------BOUNDARY--

### Get allergens
GET {{baseUrl}}/misc/allergen
Content-Type: application/json

### Get options
GET {{baseUrl}}/misc/option
Content-Type: application/json

### Post user
POST {{baseUrl}}/user/register
Content-Type: application/json
Accept: application/json

{
  "username": "testuser",
  "password": "user",
  "email": "user@email.com",
  "phone_number": "+35812345678",
  "address": "Street 12, Helsinki"
}
