@baseUrl = https://test.onesnzeroes.dev/api/v1

### Get all products
GET {{baseUrl}}/product/all
Accept: application/json

### Add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json

{
  "name": "Cheeseburger",
  "price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2],
  "default_product": true
}

### broken add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json

{
  "product_name": "Cheeseburger",
  "product_price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2],
  "default_product": true
}

### Update a product (not implemented)
PUT {{baseUrl}}/product/1
Content-Type: application/json

{
  "price": 9.99
}

### Delete a product (not implemented)
DELETE {{baseUrl}}/product/1

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "alice",
  "password": "pass123"
}

### Get me
GET {{baseUrl}}/auth/me
Accept: application/json

### Get me with invalid token
GET {{baseUrl}}/auth/me
Accept: application/json

### Get me with valid token
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MzM5MDI0MSwiZXhwIjoxNzYzNDc2NjQxfQ.TePQ7UWQVfiJ9N_RRoPMWbtOoFm0gbrUU-n2oJq7vMQ

### Get user by id
GET {{baseUrl}}/user/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MzM5MDI0MSwiZXhwIjoxNzYzNDc2NjQxfQ.TePQ7UWQVfiJ9N_RRoPMWbtOoFm0gbrUU-n2oJq7vMQ
Accept: application/json

### Get all users
GET {{baseUrl}}/user/all
Accept: application/json
Authorization: Bearer totallyvalid69token

### Post user
POST {{baseUrl}}/user/register
Content-Type: application/json
Accept: application/json

{
  "role": "user",
  "username": "illorder",
  "password": "fuckme?",
  "email": "email@provider.com"
}

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "illorder",
  "password": "fuckme?"
}