//@baseUrl = https://test.onesnzeroes.dev/api/v1
@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2Mzk5MjAxMiwiZXhwIjoxNzY0MDc4NDEyfQ.4lghtry1EFRnUR-_eoQgGtdSQsRF1I0va2Zkird5uIc
### Get all products
GET {{baseUrl}}/product/all
Accept: application/json

### Add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Cheeseburger",
  "price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2],
  "default_product": true
}

### broken add a new product
POST {{baseUrl}}/product/add
Content-Type: application/json

{
  "product_name": "Cheeseburger",
  "product_price": 8.99,
  "description": "Classic burger with cheese",
  "image_url": "burger.jpg",
  "category": "main",
  "option_ids": [1,2,4],
  "allergen_ids": [1,2]
}

### Update a product (not implemented)
PUT {{baseUrl}}/product/6
Content-Type: application/json

{
  "price": 9.99
}

### Delete a product (not implemented)
DELETE {{baseUrl}}/product/1

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "alice",
  "password": "pass123"
}

### Get me
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImlsbG9yZGVyIiwiZW1haWwiOiJlbWFpbEBwcm92aWRlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2Mzk5MTI5OSwiZXhwIjoxNzY0MDc3Njk5fQ.1VGdTnn1Jl7DoXljv816Eo8VmQtxJO_S4QePrg6EG98 


### Get me with invalid token
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer {{token}}


### Get me with valid token
GET {{baseUrl}}/auth/me
Accept: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseUrl}}/user/4
Authorization: Bearer {{token}}
Accept: application/json

### Get all users
GET {{baseUrl}}/user/all
Accept: application/json
Authorization: Bearer {{token}}

### Post user
POST {{baseUrl}}/user/register
Content-Type: application/json
Accept: application/json

{
  "role": "user",
  "username": "illorder",
  "password": "fuckme?",
  "email": "email@provider.com"
}

### Post login
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "illorder",
  "password": "fuckme?"
}

### Get orders
GET {{baseUrl}}/order/all
Accept: application/json
Authorization: Bearer {{token}}

### Post order
POST {{baseUrl}}/order
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 8.99,
  "delivery_address":"delivery address",
  "user_id": 4,
  "product_ids": [6]
}